### ISSUE TITLE
AbstractTimestampThreeTenBPColumnMapper does not understand offset

### ISSUE THREAD

**Issue by ljacq** [JadiraOrg/jadira#40]
Defining the database's timezone as an offset, e.g. `jadira.usertype.databaseZone=+1` (or with `+01:00`) in the properties file, is not supported by `AbstractTimestampThreeTenBPColumnMapper` and results in the following exception being thrown:

    java.lang.IllegalStateException: Could not map Zone +01:00 to Calendar
	  at org.jadira.usertype.dateandtime.threetenbp.columnmapper.AbstractTimestampThreeTenBPColumnMapper.getHibernateType(AbstractTimestampThreeTenBPColumnMapper.java:59)
	  at org.jadira.usertype.dateandtime.threetenbp.columnmapper.AbstractTimestampThreeTenBPColumnMapper.getHibernateType(AbstractTimestampThreeTenBPColumnMapper.java:27)
	  at org.jadira.usertype.spi.shared.AbstractSingleColumnUserType.doNullSafeGet(AbstractSingleColumnUserType.java:85)

The corresponding code is:

```java
public final DstSafeTimestampType getHibernateType() {
	
	if (databaseZone == null) {
		return DstSafeTimestampType.INSTANCE;
	}
	
	Calendar cal = resolveCalendar(databaseZone);
	if (cal == null) {
		throw new IllegalStateException("Could not map Zone " + databaseZone + " to Calendar");
	}
	
	return new DstSafeTimestampType(cal);
}

private Calendar resolveCalendar(ZoneOffset databaseZone) {
	
	String id = databaseZone.getId();
	if (Arrays.binarySearch(TimeZone.getAvailableIDs(), id) != -1) {
		return Calendar.getInstance(TimeZone.getTimeZone(id));
	} else {
		return null;
	}
}
```

The method `resolveCalendar` is called with `id` = `+01:00`, but `TimeZone.getAvailableIDs()` only contains timezone IDs such as `Europe/Paris` or `CET`.

**Comment by chrisphe** [comment]
Please review
